truncate table xijiaweb.undergraduate_students;
insert into xijiaweb.undergraduate_students
  (
   sno,
   sname,
   name_spelling,
   ever_name,
   gender_code,
   birth_date,
   nation_code,
   identify_type,
   identify_num,
   native_place,
   political_code,
   origin_place_code,
   native_province,
   account_address_code,
   cultivation_type_code,
   department_code,
   major_code,
   stu_type,
   admission_date,
   admission_grade,
   schooling_period,
   class_no,
   campus_code,
   school_state_code)
  select 
         xh       sno,
         xm       sname,
         xmpy     name_spelling,
         cym      ever_name,
         xbdm     gender_code,
         csrq     birth_date,
         mzdm     nation_code,
         sfzjlxdm identify_type,
         sfzjh    identify_num,
         jgdm     native_place,
         zzmmdm   political_code,
         syddm    origin_place_code,
         hssbkdm  native_province,
         hkszd    account_address_code,
         pyfsdm   cultivation_type_code,
         dwdm     department_code,
         zydm     major_code,
         xslx   stu_type,
         rxrq     admission_date,
         rxnj     admission_grade,
         xznj     schooling_period,
         bh       class_no,
         '01'     campus_code,
         xjztdm   school_state_code
    from xj_ryxx.t_d_xsxx
   where partid = '13';
commit;
