select * from USR_HR.T_GHGZSZGL_DL
select * from USR_HR.T_GHGZSZGL_LB
select * from USR_HR.T_KQGL_QJSJDZDB
select * from USR_HR.T_KQGL_QQB
select * from USR_HR.T_KQGL_QQLBB
select * from USR_HR.T_HTGL_HTXX
select * from USR_HR.T_HTGL_JCHTLBB
select * from USR_HR.T_ZZGL_SSLXDM
select * from USR_HR.T_ZZGL_XZDWLB
